// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerSphere.Data;

#nullable disable

namespace SoccerSphere.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20251122090236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoccerSphere.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Assists = 7,
                            Country = "Spain",
                            Goals = 6,
                            MatchesPlayed = 8,
                            PlayerName = "Pedri",
                            Rating = 8.1999999999999993,
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 2,
                            Assists = 7,
                            Country = "Spain",
                            Goals = 6,
                            MatchesPlayed = 8,
                            PlayerName = "Pedri",
                            Rating = 8.1999999999999993,
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 3,
                            Assists = 4,
                            Country = "Poland",
                            Goals = 12,
                            MatchesPlayed = 10,
                            PlayerName = "Robert Lewandowski",
                            Rating = 8.5,
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 4,
                            Assists = 5,
                            Country = "Spain",
                            Goals = 3,
                            MatchesPlayed = 9,
                            PlayerName = "Gavi",
                            Rating = 7.9000000000000004,
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 5,
                            Assists = 1,
                            Country = "Uruguay",
                            Goals = 1,
                            MatchesPlayed = 9,
                            PlayerName = "Ronald Araújo",
                            Rating = 7.7999999999999998,
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 6,
                            Assists = 0,
                            Country = "Germany",
                            Goals = 0,
                            MatchesPlayed = 9,
                            PlayerName = "Marc-André ter Stegen",
                            Rating = 8.0999999999999996,
                            TeamId = 1
                        },
                        new
                        {
                            PlayerId = 7,
                            Assists = 6,
                            Country = "France",
                            Goals = 14,
                            MatchesPlayed = 11,
                            PlayerName = "Kylian Mbappé",
                            Rating = 9.0,
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 8,
                            Assists = 7,
                            Country = "Brazil",
                            Goals = 8,
                            MatchesPlayed = 10,
                            PlayerName = "Vinícius Júnior",
                            Rating = 8.4000000000000004,
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 9,
                            Assists = 5,
                            Country = "England",
                            Goals = 10,
                            MatchesPlayed = 11,
                            PlayerName = "Jude Bellingham",
                            Rating = 8.6999999999999993,
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 10,
                            Assists = 0,
                            Country = "Belgium",
                            Goals = 0,
                            MatchesPlayed = 8,
                            PlayerName = "Thibaut Courtois",
                            Rating = 8.3000000000000007,
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 11,
                            Assists = 2,
                            Country = "Austria",
                            Goals = 2,
                            MatchesPlayed = 9,
                            PlayerName = "David Alaba",
                            Rating = 7.9000000000000004,
                            TeamId = 2
                        },
                        new
                        {
                            PlayerId = 12,
                            Assists = 3,
                            Country = "Norway",
                            Goals = 15,
                            MatchesPlayed = 11,
                            PlayerName = "Erling Haaland",
                            Rating = 9.0999999999999996,
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 13,
                            Assists = 6,
                            Country = "England",
                            Goals = 7,
                            MatchesPlayed = 11,
                            PlayerName = "Phil Foden",
                            Rating = 8.5,
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 14,
                            Assists = 7,
                            Country = "Portugal",
                            Goals = 4,
                            MatchesPlayed = 10,
                            PlayerName = "Bernardo Silva",
                            Rating = 8.1999999999999993,
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 15,
                            Assists = 0,
                            Country = "Portugal",
                            Goals = 1,
                            MatchesPlayed = 10,
                            PlayerName = "Rúben Dias",
                            Rating = 7.7999999999999998,
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 16,
                            Assists = 4,
                            Country = "England",
                            Goals = 3,
                            MatchesPlayed = 9,
                            PlayerName = "Jack Grealish",
                            Rating = 7.9000000000000004,
                            TeamId = 3
                        },
                        new
                        {
                            PlayerId = 17,
                            Assists = 6,
                            Country = "Norway",
                            Goals = 6,
                            MatchesPlayed = 10,
                            PlayerName = "Martin Ødegaard",
                            Rating = 8.4000000000000004,
                            TeamId = 4
                        },
                        new
                        {
                            PlayerId = 18,
                            Assists = 8,
                            Country = "England",
                            Goals = 9,
                            MatchesPlayed = 11,
                            PlayerName = "Bukayo Saka",
                            Rating = 8.8000000000000007,
                            TeamId = 4
                        },
                        new
                        {
                            PlayerId = 19,
                            Assists = 4,
                            Country = "England",
                            Goals = 2,
                            MatchesPlayed = 8,
                            PlayerName = "Declan Rice",
                            Rating = 6.7000000000000002,
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("SoccerSphere.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("Loses")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Country = "Spain",
                            Draws = 1,
                            Loses = 2,
                            Revenue = 100000000m,
                            TeamName = "Barcelona",
                            Wins = 9
                        },
                        new
                        {
                            TeamId = 2,
                            Country = "Spain",
                            Draws = 1,
                            Loses = 3,
                            Revenue = 200000000m,
                            TeamName = "Real Madrid",
                            Wins = 8
                        },
                        new
                        {
                            TeamId = 3,
                            Country = "England",
                            Draws = 1,
                            Loses = 1,
                            Revenue = 150000000m,
                            TeamName = "Manchester City",
                            Wins = 10
                        },
                        new
                        {
                            TeamId = 4,
                            Country = "England",
                            Draws = 2,
                            Loses = 1,
                            Revenue = 120000000m,
                            TeamName = "Arsenal",
                            Wins = 9
                        });
                });

            modelBuilder.Entity("SoccerSphere.Models.Player", b =>
                {
                    b.HasOne("SoccerSphere.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
