// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerSphere.Data;


#nullable disable

namespace SoccerSphere.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20251110182323_AddSampleData")]
    partial class AddSampleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoccerSphere.Models.League", b =>
                {
                    b.Property<int>("leagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("leagueId"));

                    b.Property<string>("leagueContinent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leagueCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leagueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("leagueId");

                    b.ToTable("leagues");
                });

            modelBuilder.Entity("SoccerSphere.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("PlayerId");

                    b.ToTable("players");
                });

            modelBuilder.Entity("SoccerSphere.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("Loses")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Country = "Spain",
                            Draws = 1,
                            Loses = 2,
                            Revenue = 100000000m,
                            TeamName = "Barcelona",
                            Wins = 9
                        },
                        new
                        {
                            TeamId = 2,
                            Country = "Spain",
                            Draws = 1,
                            Loses = 3,
                            Revenue = 200000000m,
                            TeamName = "Real Madrid",
                            Wins = 8
                        },
                        new
                        {
                            TeamId = 3,
                            Country = "England",
                            Draws = 1,
                            Loses = 1,
                            Revenue = 150000000m,
                            TeamName = "Manchester City",
                            Wins = 10
                        },
                        new
                        {
                            TeamId = 4,
                            Country = "England",
                            Draws = 2,
                            Loses = 1,
                            Revenue = 120000000m,
                            TeamName = "Arsenal",
                            Wins = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
