// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoccerSphere.Models;

#nullable disable

namespace SoccerSphere.Migrations
{
    [DbContext(typeof(TeamContext))]
    [Migration("20251119175505_UpdatePlayerSeedDataWithTeamId")]
    partial class UpdatePlayerSeedDataWithTeamId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoccerSphere.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Assists = 0,
                            Country = "Spain",
                            Goals = 0,
                            MatchesPlayed = 0,
                            PlayerName = "Pedri",
                            Rating = 0.0,
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("SoccerSphere.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("Loses")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.ToTable("teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Country = "Spain",
                            Draws = 1,
                            Loses = 2,
                            Revenue = 100000000m,
                            TeamName = "Barcelona",
                            Wins = 9
                        },
                        new
                        {
                            TeamId = 2,
                            Country = "Spain",
                            Draws = 1,
                            Loses = 3,
                            Revenue = 200000000m,
                            TeamName = "Real Madrid",
                            Wins = 8
                        },
                        new
                        {
                            TeamId = 3,
                            Country = "England",
                            Draws = 1,
                            Loses = 1,
                            Revenue = 150000000m,
                            TeamName = "Manchester City",
                            Wins = 10
                        },
                        new
                        {
                            TeamId = 4,
                            Country = "England",
                            Draws = 2,
                            Loses = 1,
                            Revenue = 120000000m,
                            TeamName = "Arsenal",
                            Wins = 9
                        });
                });

            modelBuilder.Entity("SoccerSphere.Models.Player", b =>
                {
                    b.HasOne("SoccerSphere.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
